ansible_user: admin
ansible_password: pass
ansible_connection: network_cli
ansible_port: 22
ansible_become: yes
ansible_become_method: enable
ansible_become_password: pass
ansible_network_os: ios