- name: Configuring Host Settings
  tags: host
  cisco.ios.ios_config:
    src: '../templates/hesno.j2'

- name: Configuring Interfaces
  tags: int
  cisco.ios.ios_config:
    src: '../templates/interfaces.j2'

- name: Configuring Routing
  tags: ospf
  cisco.ios.ios_config:
    src: '../templates/ospf.j2'
