- name: Deploy CoreTAAS
  hosts: ctaas_91
  gather_facts: False

  tasks:
    - include_tasks: '../playbooks/deploy_ctaas.yml'

- name: Deploy CoreBABA
  hosts: cbaba_91
  gather_facts: False

  tasks:
    - include_tasks: '../playbooks/deploy_cbaba.yml'

- name: Deploy CUCM
  hosts: cucm_91
  gather_facts: False

  tasks:
    - include_tasks: '../playbooks/deploy_cucm.yml'

- name: Deploy EDGE
  hosts: edge_91
  gather_facts: False

  tasks:
    - include_tasks: '../playbooks/deploy_edge.yml'
