- name: Deploy CoreTAAS
  hosts: ctaas_62
  gather_facts: False
  include_vars: '../group_vars/day1_devices.yml'

  tasks:
    - name: Initialization
      include_vars: '../host_vars/ctaas_62.yml'
    - include_tasks: '../playbooks/deploy_ctaas.yml'

- name: Deploy CoreBABA
  hosts: cbaba_62
  gather_facts: False

  tasks:
    - name: Initialization
      include_vars: '../host_vars/cbaba_62.yml'
    - include_tasks: '../playbooks/deploy_cbaba.yml'

- name: Deploy CUCM
  hosts: cucm_62
  gather_facts: False

  tasks:
    - name: Initialization
      include_vars: '../host_vars/cucm_62.yml'
    - include_tasks: '../playbooks/deploy_cucm.yml'

- name: Deploy EDGE
  hosts: edge_62
  gather_facts: False

  tasks:
    - name: Initialization
      include_vars: '../host_vars/edge_62.yml'
    - include_tasks: '../playbooks/deploy_edge.yml'