- name: Deploy CoreTAAS
  hosts: ctaas_91
  gather_facts: False
  include_vars: '../group_vars/day1_devices.yml'

  tasks:
    - name: Initialization
      include_vars: '../host_vars/ctaas_91.yml'
    - include_tasks: '../playbooks/deploy_ctaas.yml'

- name: Deploy CoreBABA
  hosts: cbaba_91
  gather_facts: False

  tasks:
    - name: Initialization
      include_vars: '../host_vars/cbaba_91.yml'
    - include_tasks: '../playbooks/deploy_cbaba.yml'

- name: Deploy CUCM
  hosts: cucm_91
  gather_facts: False

  tasks:
    - name: Initialization
      include_vars: '../host_vars/cucm_91.yml'
    - include_tasks: '../playbooks/deploy_cucm.yml'

- name: Deploy EDGE
  hosts: edge_91
  gather_facts: False

  tasks:
    - name: Initialization
      include_vars: '../host_vars/edge_91.yml'
    - include_tasks: '../playbooks/deploy_edge.yml'