- name: Deploy CoreTAAS
  hosts: ctaas_72
  gather_facts: False

  tasks:
    - include_tasks: '../playbooks/deploy_ctaas.yml'

- name: Deploy CoreBABA
  hosts: cbaba_72
  gather_facts: False

  tasks:
    - include_tasks: '../playbooks/deploy_cbaba.yml'

- name: Deploy CUCM
  hosts: cucm_72
  gather_facts: False

  tasks:
    - include_tasks: '../playbooks/deploy_cucm.yml'

- name: Deploy EDGE
  hosts: edge_72
  gather_facts: False

  tasks:
    - include_tasks: '../playbooks/deploy_edge.yml'
