- name: Deploy CoreTAAS
  hosts: ctaas_81
  gather_facts: False
  include_vars: '../group_vars/day1_devices.yml'

  tasks:
    - name: Initialization
      include_vars: '../host_vars/ctaas_81.yml'
    - include_tasks: '../playbooks/deploy_ctaas.yml'

- name: Deploy CoreBABA
  hosts: cbaba_81
  gather_facts: False

  tasks:
    - name: Initialization
      include_vars: '../host_vars/cbaba_81.yml'
    - include_tasks: '../playbooks/deploy_cbaba.yml'

- name: Deploy CUCM
  hosts: cucm_81
  gather_facts: False

  tasks:
    - name: Initialization
      include_vars: '../host_vars/cucm_81.yml'
    - include_tasks: '../playbooks/deploy_cucm.yml'

- name: Deploy EDGE
  hosts: edge_81
  gather_facts: False

  tasks:
    - name: Initialization
      include_vars: '../host_vars/edge_81.yml'
    - include_tasks: '../playbooks/deploy_edge.yml'